config/routes.rb
Grummle::Application.routes.draw do
  resources :notes do
    resources :share
  end

  get 'about' => 'pages#about'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'edituser' => 'users#edit'
  patch 'edituser' => 'users#update'
  get 'activate' => 'users#activate'
  get 'resend_activation' => 'users#resend_activation'
  get 'forgot_password' => 'users#forgot_password'
  post 'reset_password' => 'users#reset_password'
  get 'new_password' => 'users#new_password'
  patch 'update_password' => 'users#update_password'
  get 'update_email' => 'users#update_email'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'auth/:provider/callback' => 'sessions#create_oauth'
  get 'auth/failure' => 'sessions#oauth_failed'

  root 'notes#index'
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :shares, dependent: :destroy

  validates :title, length: { minimum: 4 }
  validates :text, presence: true

  before_create :generate_permalink

  def to_param
    self.permalink
  end

  def generate_permalink
    begin
      link = SecureRandom.urlsafe_base64(8)
    end while Note.exists?(permalink: link)
    self.permalink = link
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_login, except: :show
  helper_method :my_note?
  helper_method :shared_with_me?

  def index
  end

  def create
    @note = current_user.notes.new(note_params)
    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end

  def new
    @note = current_user.notes.new
  end

  def edit
    @note = Note.find_by_permalink!(params[:id])
    if !my_note?(@note) && !shared_with_me?(@note)
      flash_message :danger, t(:nopermission)
      redirect_to notes_path
    end
  end

  def show
    @note = Note.find_by_permalink(params[:id])
    if @note
      unless @note.public
        require_login
        return unless current_user
        if !my_note?(@note) && !shared_with_me?(@note)
          flash_message :danger, t(:notfound)
          redirect_to notes_path
        end
      end
    else
      flash_message :danger, t(:notfound)
      redirect_to notes_path
    end
  end

  def update
    @note = Note.find_by_permalink!(params[:id])
    if !my_note?(@note) && !shared_with_me?(@note)
      flash_message :danger, t(:nopermission)
      redirect_to notes_path
    else
      if @note.update(note_params)
        redirect_to @note
      else
        render 'edit'
      end
    end
  end

  def destroy
    @note = current_user.notes.find_by_permalink!(params[:id])
    @note.destroy
    redirect_to notes_path
  end

  private
    def note_params
      params.require(:note).permit(:title, :text, :public)
    end

    def my_note?(note)
      current_user && current_user.id == note.user_id
    end

    def shared_with_me?(note)
      current_user && current_user.shares.find_by_note_id(note.id)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
  def markdown(text)
    sanitize GitHub::Markdown.render_gfm(text)
  end
end

app/views/notes/_form.html.erb
<%= form_for @note do |f| %>
  <% if @note.errors.any? %>
    <div class="alert alert-danger">
      <b><%= t :noteerror %></b>
      <ul>
        <% @note.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="checkbox">
    <%= f.label :public do %>
      <%= f.check_box :public %><%= t 'note.public' %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :text %><br>
    <%= f.text_area :text, class: 'form-control', autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'pull-right btn btn-success' %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1><%= t :edit %></h1>
<%= render 'form' %>
<p><%= link_to t(:back), @note %></p>

app/views/notes/index.html.erb
<%= render 'shared/flash' %>
<div class="panel panel-default">
  <div class="panel-heading">
    <table class="full">
      <tr>
        <td><b class="panel-title"><%= t :notes %></b></td>
        <td class="text-right">
          <%= link_to new_note_path, class: 'btn btn-success' do %>
            <i class="fas fa-plus"></i> <%= t :newnote %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
  <ul class="list-group">
    <% current_user.notes.order(updated_at: :desc).each do |note| %>
      <%= link_to note.title, note, class: 'list-group-item' %>
    <% end %>
  </ul>
</div>
<% if current_user.shares.any? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <b class="panel-title"><%= t :sharedwithme %></b>
    </div>
    <ul class="list-group">
      <% current_user.shares.includes(:note).order('notes.updated_at DESC').each do |share| %>
        <%= link_to share.note.title, share.note, class: 'list-group-item' %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/notes/new.html.erb
<h1><%= t :newnote %></h1>
<%= render 'form' %>
<p><%= link_to t(:back), notes_path %></p>

app/views/notes/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <table class="full">
      <tr>
        <td>
          <b class="panel-title"><%= @note.title %></b>
          <% if @note.public || @note.shares.any? %>
            <br>
            <i>
              <%= t(:createdby).titleize %>: <%= @note.user.username %>
              <% if @note.shares.any? %>
                <br><%= t(:sharedwith).titleize %>: <%= @note.shares.collect{|share| share.user.username}.join(", ") %>
              <% end %>
              <% if @note.public %>
                <br><%= t :publichint %>
              <% end %>
            </i>
          <% end %>
        </td>
        <td class="text-right">
          <% if my_note?(@note) || shared_with_me?(@note) %>
            <%= link_to edit_note_path(@note), class: 'btn btn-success' do %>
              <i class="fas fa-edit"></i> <%= t :edit %>
            <% end %>
          <% end %>
          <% if my_note?(@note) %>
            <%= link_to note_share_index_path(@note), class: 'btn btn-info' do %>
              <i class="fas fa-share"></i> <%= t :share %>
            <% end %>
            <button class="btn btn-danger" data-toggle="modal" data-target="#dlgDelete">
              <i class="fas fa-remove"></i> <%= t :delete %>
            </button>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
  <div class="panel-body">
    <%= markdown(@note.text) %>
  </div>
</div>
<p><%= link_to t(:back), notes_path %></p>

<% if my_note?(@note) %>
  <!-- Delete Dialog -->
  <div class="modal fade" id="dlgDelete" tabindex="-1" role="dialog" aria-labelledby="lblDelete" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="lblDelete"><%= @note.title %></h4>
        </div>
        <div class="modal-body">
          <%= t :confirmremovenote %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= link_to t(:delete), @note, method: :delete, class: 'btn btn-danger' %>
        </div>
      </div>
    </div>
  </div>
<% end %>