config/routes.rb
Grummle::Application.routes.draw do
  resources :notes do
    resources :share
  end

  get 'about' => 'pages#about'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'edituser' => 'users#edit'
  patch 'edituser' => 'users#update'
  get 'activate' => 'users#activate'
  get 'resend_activation' => 'users#resend_activation'
  get 'forgot_password' => 'users#forgot_password'
  post 'reset_password' => 'users#reset_password'
  get 'new_password' => 'users#new_password'
  patch 'update_password' => 'users#update_password'
  get 'update_email' => 'users#update_email'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'auth/:provider/callback' => 'sessions#create_oauth'
  get 'auth/failure' => 'sessions#oauth_failed'

  root 'notes#index'
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :note
  belongs_to :user
end

app/controllers/share_controller.rb
class ShareController < ApplicationController
  before_action :require_note_owner

  def index
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.id != current_user.id && !@note.shares.find_by_user_id(user.id)
      share = @note.shares.new(user_id: user.id)
      share.save!
      ShareMailer.note_shared_email(@note, user).deliver_now
      flash_message :success, t(:noteshared)
    else
      flash_message :danger, t(:sharingfailed)
    end
    redirect_to note_share_index_path
  end

  def destroy
    share = @note.shares.find_by_id!(params[:id])
    share.destroy!
    redirect_to note_share_index_path
  end

  private
    def require_note_owner
      require_login
      return unless current_user
      @note = current_user.notes.find_by_permalink(params[:note_id])
      unless @note
        flash_message :danger, t(:nopermission)
        redirect_to notes_path
      end
    end
end

app/views/share/index.html.erb
<%= render 'shared/flash' %>
<div class="panel panel-default">
  <div class="panel-heading">
    <table class="full">
      <tr>
        <td><b class="panel-title"><%= @note.title %> <%= t :sharedwith %></b></td>
        <td class="text-right">
          <button class="btn btn-success" data-toggle="modal" data-target="#dlgAdd">
            <i class="fas fa-plus"></i> <%= t :add %>
          </button>
        </td>
      </tr>
    </table>
  </div>
  <ul class="list-group">
    <% @note.shares.each do |share| %>
      <li class="list-group-item">
        <a class="close" data-toggle="modal" data-target="#dlgDelete<%= share.id %>">&times;</a>
        <!-- Delete Dialog -->
        <div class="modal fade" id="dlgDelete<%= share.id %>" tabindex="-1" role="dialog" aria-labelledby="lblDelete<%= share.id %>" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="lblDelete<%= share.id %>"><%= share.user.username %></h4>
              </div>
              <div class="modal-body">
                <%= t :confirmremoveshare %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <%= link_to t(:delete), note_share_path(@note, share), method: :delete, class: 'btn btn-danger' %>
              </div>
            </div>
          </div>
        </div>
        <!-- Delete Dialog End -->
        <%= share.user.username %>
      </li>
    <% end %>
  </ul>
</div>
<%= link_to t(:back), @note %>

<!-- Add Dialog -->
<div class="modal fade" id="dlgAdd" tabindex="-1" role="dialog" aria-labelledby="lblAdd" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="lblAdd"><%= t :share %></h4>
      </div>
      <%= form_tag note_share_index_path do %>
        <div class="modal-body">
          <div class="form-group">
            <%= label_tag :username, t('user.username') %><br>
            <%= text_field_tag :username, params[:username], class: 'form-control', autofocus: true %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= submit_tag t(:add), class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>