config/routes.rb
Grummle::Application.routes.draw do
  resources :notes do
    resources :share
  end

  get 'about' => 'pages#about'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'edituser' => 'users#edit'
  patch 'edituser' => 'users#update'
  get 'activate' => 'users#activate'
  get 'resend_activation' => 'users#resend_activation'
  get 'forgot_password' => 'users#forgot_password'
  post 'reset_password' => 'users#reset_password'
  get 'new_password' => 'users#new_password'
  patch 'update_password' => 'users#update_password'
  get 'update_email' => 'users#update_email'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'auth/:provider/callback' => 'sessions#create_oauth'
  get 'auth/failure' => 'sessions#oauth_failed'

  root 'notes#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :notes, dependent: :destroy
  has_many :shares, dependent: :destroy
  has_many :authorizations, dependent: :destroy

  validates :username, uniqueness: { case_sensitive: false }, length: { in: 3..70 }
  validates :email, uniqueness: { case_sensitive: false }, format: { with: /\S+@\S+\.\w+/ }
  validates :password, length: { minimum: 7 }, allow_nil: true

  before_save :generate_tokens

  def generate_tokens
    begin
      token = SecureRandom.urlsafe_base64
    end while User.exists?(auth_token: token)
    self.auth_token = token
    begin
      token = SecureRandom.urlsafe_base64
    end while User.exists?(update_token: token)
    self.update_token = token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:edit, :update]

  # Sign up
  def new
    @user = User.new
  end

  def create
    @user = User.new(new_user_params)
    @user.activated = false
    if @user.save
      UserMailer.registered_email(@user).deliver_now
      flash_message :success, t(:accountcreated)
      redirect_to login_path
    else
      render 'new'
    end
  end

  # Changing account information
  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if params[:user][:username] != @user.username
      @user.username = params[:user][:username]
      if @user.save
        cookies[:auth_token] = @user.auth_token
        flash_now :success, t(:usernamechanged)
      else
        @user.reload
      end
    end
    if @user.authenticate(params[:password_old])
      if !params[:user][:password].blank? && @user.update(change_password_params)
          cookies[:auth_token] = @user.auth_token
          flash_now :success, t(:passwordchanged)
      end
      if params[:user][:email] != @user.email
        @user.email = params[:user][:email]
        if @user.valid?
          UserMailer.change_email_email(@user).deliver_now
          flash_now :warning, t(:emailchange)
        end
      end
    else
      flash_now :danger, t(:pwdoesnotmatch) if !params[:user][:password].blank? || params[:user][:email] != @user.email
    end
    @user.reload
    render 'edit'
  end

  # E-Mail verification
  def activate
    @user = User.find_by!(username: params[:username], update_token: params[:token], activated: false)
    @user.activated = true
    @user.save!
    flash_message :success, t(:activated)
    redirect_to login_path
  end

  def resend_activation
    @user = User.find_by!(username: params[:username], activated: false)
    UserMailer.activation_email(@user).deliver_now
    flash_message :success, t(:activationrequested)
    redirect_to login_path
  end

  def update_email
    @user = User.find_by!(username: params[:username], update_token: params[:token])
    @user.email = params[:email]
    @user.save!
    cookies[:auth_token] = @user.auth_token
    flash_message :success, t(:emailchangeconfirmed)
    redirect_to notes_path
  end

  # Password reset
  def forgot_password
  end

  def reset_password
    @user = User.find_by(username: params[:username], email: params[:email])
    if @user
      UserMailer.password_email(@user).deliver_now
      flash_message :success, t(:passwordresetemail)
      redirect_to login_path
    else
      flash_now :danger, t(:accountnotfound)
      render 'forgot_password'
    end
  end

  def new_password
    @user = User.find_by!(username: params[:username], update_token: params[:token])
  end

  def update_password
    @user = User.find_by!(username: params[:username], update_token: params[:token])
    if @user.update(change_password_params)
      flash_message :success, t(:passwordchanged)
      redirect_to login_path
    else
      render 'new_password'
    end
  end

  # Params
  private
    def new_user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def change_password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/views/users/edit.html.erb
<h1><%= t :edituser %></h1>
<%= form_for @user, url: edituser_path do |f| %>
  <%= render 'shared/flash' %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <b><%= t :usererror %></b>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: 'form-control', autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= label_tag :password_old, t('user.password_old') %><br>
    <%= password_field_tag :password_old, params[:password_old], class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, t('user.password_new') %><br>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'pull-right btn btn-success' %>
  </div>
<% end %>
<%= link_to t(:back), notes_path %>

app/views/users/forgot_password.html.erb
<h1><%= t :resetpassword %></h1>
<%= form_tag reset_password_path do |f| %>
  <%= render 'shared/flash' %>
  <div class="form-group">
    <%= label_tag :username, t('user.username') %>
    <%= text_field_tag :username, params[:username], class: 'form-control', autofocus: true %>
  </div>
  <div class="form-group">
    <%= label_tag :email, t('user.email') %><br>
    <%= email_field_tag :email, params[:email], class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= submit_tag t(:resetpassword), class: 'pull-right btn btn-success' %>
  </div>
<% end %>
<%= link_to t(:back), login_path %>

app/views/users/new.html.erb
<h1><%= t :signup %></h1>
<%= form_for @user, url: signup_path do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <b><%= t :usererror %></b>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: 'form-control', autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.email_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password %><br>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'pull-right btn btn-success' %>
  </div>
<% end %>
<%= link_to t(:back), notes_path %>

app/views/users/new_password.html.erb
<h1><%= t :changepassword %></h1>
<%= form_for @user, url: update_password_path(username: params[:username], token: params[:token]), method: :patch do |f| %>
  <%= render 'shared/flash' %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <b><%= t :usererror %></b>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :password %><br>
    <%= f.password_field :password, class: 'form-control', autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit t(:changepassword), class: 'pull-right btn btn-success' %>
  </div>
<% end %>
<%= link_to t(:back), login_path %>