config/routes.rb
Grummle::Application.routes.draw do
  resources :notes do
    resources :share
  end

  get 'about' => 'pages#about'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'edituser' => 'users#edit'
  patch 'edituser' => 'users#update'
  get 'activate' => 'users#activate'
  get 'resend_activation' => 'users#resend_activation'
  get 'forgot_password' => 'users#forgot_password'
  post 'reset_password' => 'users#reset_password'
  get 'new_password' => 'users#new_password'
  patch 'update_password' => 'users#update_password'
  get 'update_email' => 'users#update_email'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'auth/:provider/callback' => 'sessions#create_oauth'
  get 'auth/failure' => 'sessions#oauth_failed'

  root 'notes#index'
end

app/helpers/layouts_helper.rb
module LayoutsHelper
  def active_page(page)
    'active' if current_page?(page)
  end

  def active_controller(controller)
    'active' if controller_name == controller
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="sr-only">Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Grummle', notes_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav">
        <%= content_tag :li, class: active_controller('notes') || active_controller('share') do %>
          <%= link_to t(:notes), notes_path %>
        <% end %>
        <%= content_tag :li, class: active_page(about_path) do %>
          <%= link_to t(:about), about_path %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <p class="navbar-text"><%= t :signedinas, user: current_user.username %></p>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle bs-tooltip" data-toggle="dropdown" title="<%= t :language %>">
            <i class="fas fa-language fa-lg-nav"></i> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to url_for(loc: :en) do %>
                <i class="famfamfam-flag-gb"></i> English
              <% end %>
            </li>
            <li>
              <%= link_to url_for(loc: :de) do %>
                <i class="famfamfam-flag-de"></i> Deutsch
              <% end %>
            </li>
          </ul>
        </li>
        <% unless current_user %>
          <li><%= link_to t(:signup), signup_path %></li>
          <li><%= link_to t(:login), login_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle bs-tooltip" data-toggle="dropdown" title="<%= t :account %>">
              <i class="fas fa-user fa-lg-nav"></i> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to new_note_path do %>
                  <i class="fas fa-plus"></i> <%= t :newnote %>
                <% end %>
              </li>
              <li>
                <%= link_to edituser_path do %>
                  <i class="fas fa-cog"></i> <%= t :edituser %>
                <% end %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to logout_path do %>
                  <i class="fas fa-sign-out-alt"></i> <%= t :logout %>
                <% end %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <title>Grummle</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Grummle is an easy and minimalistic system that allows you to manage personal notes.">
  <link href="//fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload', defer: true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
  <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js" defer></script>
  <script>
  window.addEventListener("turbolinks:load", function(){
  window.cookieconsent.initialise({
    "palette": {
      "popup": {
        "background": "#efefef",
        "text": "#404040"
      },
      "button": {
        "background": "#8ec760",
        "text": "#ffffff"
      }
    },
    "theme": "classic"
  })});
  </script>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div id="container" class="container">
    <main>
      <%= yield %>
    </main>
  </div>
</body>
</html>